### ISSUE TITLE
allow for focus to leave EditBox

### ISSUE THREAD

**Issue by wgahnagl** [cschreib/lxgui#64] opened 2021-03-27 22:43 UTC
Hello again! 
So I've hit my first issue with the library! 
It looks like writing text in the textbox is working fine, but you're unable to leave it once you've clicked on it! 
I'm not sure if that can be solved by writing lua scripts to work around it, or if it needs to be fixed in the library itself, but either way I'll take a look :ok_hand: 

It would probably be good to be able to set a global "textbox focus" type thing that locks out all other keypresses while you're interacting with a textbox, and unsets the lockout when you click anywhere else.

**Comment by cschreib** [comment] 2021-03-28 08:10
Hello and thanks for your feedback! I think what you request is already possible :)

1. Look at the [edit box demo](https://github.com/cschreib/lxgui/blob/master/gui/bin/interface/scroll_test/templates.xml) (bottom of the file). You can hook to the OnEscapePressed event handler and call `EditBox:clear_focus`. This allows the focus to be cleared when pressing the escape key. You can also call `clear_focus` in other scripts (such as when pressing a "Submit" button associated to the edit box). Does that cover all your needs?
2. The C++ API lets you query if there's something in the interface that currently has keyboard focus. Look at line 77 in the [example for SFML](https://github.com/cschreib/lxgui/blob/master/gui/examples/sfml/main.cpp). You should check for this before processing key events for your own game logic. At the moment there is no builtin logic to "unfocus" by clicking anywhere else, however. I'll have a think about this.

**Comment by cschreib** [comment] 2021-03-28 08:39
I've pushed changes on `master` so that clicking outside of an edit box removes its focus. Let me know if that does the trick for you.

**Comment by wgahnagl** [comment] 2021-03-29 16:50
thank you so much! I'll take a look soon! :ok_hand: :fire:

**Comment by cschreib** [comment] 2021-05-31 09:38
I haven't been able to reproduce the problem since this fix has been merged. Have you had a chance to look at it and confirm it on your end? Just so I can close this ticket.

**Comment by cschreib** [comment] 2021-07-14 19:15
I'll take silence for approval :)

**Closed by cschreib** 2021-07-14 19:15 UTC
Labels: core, enhancement
